server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**, /api/auth/**
          filters:
            - name: RequestHeader
              args:
                name: Authorization
                value: Bearer 
        - id: car-catalog-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/cars/**
        - id: booking-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/bookings/**
        - id: frontend
          uri: http://localhost:8084
          predicates:
            - Path=/**

jwt:
  secret: your-secret-key-here
